// _app.js

import "@/styles/globals.css";
import React, { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { AppCacheProvider } from "@mui/material-nextjs/v13-pagesRouter";
import { ThemeProvider, createTheme } from "@mui/material/styles";
import { Roboto } from "next/font/google";
import Layout from "@/components/layout";
import useBearStore from "@/store/useBearStore";
import Head from "next/head";
import { Backdrop, CircularProgress } from "@mui/material";
import axios from "axios";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

const theme = createTheme({
  palette: {},
  typography: {
    fontFamily: roboto.style.fontFamily,
  },
});

export default function App({ Component, pageProps, props }) {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const setAppName = useBearStore((state) => state.setAppName);
  const [tasks, setTasks] = useState([]);
  const pageName = router.pathname;

  useEffect(() => {
    console.log("App load", pageName, router.query);
    setLoading(true);
    // Handle page name or other global states
    setAppName("Say Hi");

    // Fetch initial data from FastAPI
    axios.get("http://localhost:8000/api/get_tasks")
      .then((response) => {
        setTasks(response.data.tasks);
        console.log("Fetched tasks:", response.data.tasks);
      })
      .catch((error) => {
        console.error("Failed to fetch tasks:", error);
      })
      .finally(() => setLoading(false));
  }, [router, pageName]);

  return (
    <React.Fragment>
      <Head>
        <title>{`Application`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppCacheProvider {...props}>
        <ThemeProvider theme={theme}>
          <Layout>
            <Component {...pageProps} tasks={tasks} />
          </Layout>
        </ThemeProvider>
      </AppCacheProvider>
    </React.Fragment>
  );
}
